# Generated by Django 3.1.7 on 2021-03-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_title', models.CharField(max_length=20, verbose_name='Название услуги')),
                ('pc_description', models.CharField(max_length=200, verbose_name='Описание')),
                ('pc_value', models.CharField(max_length=20, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Название пакета услуг',
                'verbose_name_plural': 'Название пакета услуг',
            },
        ),
        migrations.CreateModel(
            name='PriceTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pt_title', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('pt_old_price', models.CharField(max_length=200, verbose_name='Старая цена')),
                ('pt_new_price', models.CharField(max_length=200, verbose_name='Новая цена')),
            ],
            options={
                'verbose_name': 'Услуги',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
